# netlify.toml
# This file tells Netlify how to build and deploy your site.

[build]
  command = "npx @11ty/eleventy"  # The command to build your site
  publish = "_site"               # The folder to deploy (Eleventy's output)

[context.production.environment]
  # Sets the Node.js version
  NODE_VERSION = "18"
