[build]
  publish = "."
  functions = "netlify/functions"

# Niche wala pura section delete kar do:
# [[plugins]]
#   package = "@netlify/plugin-copy-contents"
#   [plugins.inputs]
#     source = ["offers", "products", "service", "works"]
#     destination = "netlify/functions"
