backend:
  name: git-gateway
  branch: main
  # Note: Netlify Git Gateway use karne ke liye,
  # Netlify site settings mein 'Identity' aur 'Git Gateway' enable hona ZARURI hai.
  # Agar abhi bhi blank screen aaye, toh woh steps must hain.

media_folder: "uploads"          # Where uploaded files go in repo
public_folder: "/uploads"        # Public URL for those files

collections:
  - name: "offers"
    label: "Offers Banner"
    folder: "offers"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }

  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }

  - name: "services"
    label: "Services"
    folder: "service"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }

  - name: "works"
    label: "Our Works"
    folder: "works"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }
      
