backend:
  name: github
  repo: mdarkamkhan/aliflt   # 🔴 Replace this with your GitHub repo
  branch: main                   # or "master" if your repo uses master

media_folder: "uploads"          # Where uploaded files go in repo
public_folder: "/uploads"        # Public URL for those files

collections:
  - name: "offers"
    label: "Offers Banner"
    folder: "offers"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }

  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }

  - name: "services"
    label: "Services"
    folder: "service"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }

  - name: "works"
    label: "Our Works"
    folder: "works"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }
      
